### PR TITLE
👀 Mentor Application View

### LINKED ISSUE #224: Mentor Application View Modal
#### Description
if Ishaan's endpoint has not been merged yet, use a JSON of dummy data 
related to #218 and #202

#### Screenshots
image

### PR DESCRIPTION
**Pull request by Leundai**
## Description :star2:

Fixes #224 
 
## Screenshots
image

### Older Screenshot
image

## TODOs :star:
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by AngelaLuo49021 — COMMENTED** [review]
Faith changed the design from the progress bar to different colored tabs
image

**Review by AngelaLuo49021 — APPROVED** [review]
Looks great!

**Review by AngelaLuo49021 — COMMENTED** [review]
We want this connected to backend but if you want to merge this in first thats fine while we wait on ishaan's PR

**Review by kenetec — APPROVED** [review]
gucci 🐐

**Pull request merged**
