### PR TITLE
🙌 Mentee appointment connection

### LINKED ISSUE #319: Mentee Appointment Page Connection
#### Description
Similarly to the Mentor Appointment page connect the mentee appointment page

#### Tasks
- [x] Update backend endpoint if needed to display data similar to the mockdata
- [x] Connect/Create wrapper functions if needed
- [x] Test

### PR DESCRIPTION
**Pull request by Leundai**
## Description :star2:

Fixes #319 
 
## Screenshots
image
image

### CODE REVIEW

**Review by AngelaLuo49021 — CHANGES_REQUESTED** [review]
image
Showing upcoming appoitnments is not working
image
id: 60a70ea0baed90df4c8f23c9

**Review by kenetec — APPROVED** [review]
Sweeet 😍

**Comment by kenetec** [comment]
Upcoming appointments works for me
image

**Review by AngelaLuo49021 — APPROVED** [review]
Looks great!

**Pull request merged**
